// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDelMMDyiavhEWIh7wN8jgnFKvXm4fsAto',
    appId: '1:151677224326:web:ab620c27c13009e3289807',
    messagingSenderId: '151677224326',
    projectId: 'skillghor-145e9',
    authDomain: 'skillghor-145e9.firebaseapp.com',
    storageBucket: 'skillghor-145e9.firebasestorage.app',
    measurementId: 'G-YKCMXRNC08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6tB_n0ciabCBXj6Ui0y3jYXh4piGFtGU',
    appId: '1:151677224326:android:183fa0857b827979289807',
    messagingSenderId: '151677224326',
    projectId: 'skillghor-145e9',
    storageBucket: 'skillghor-145e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrIPV69WST8eYp-FSdJ6kd5l8n87SIeXE',
    appId: '1:151677224326:ios:098f57cc6b742261289807',
    messagingSenderId: '151677224326',
    projectId: 'skillghor-145e9',
    storageBucket: 'skillghor-145e9.firebasestorage.app',
    iosClientId:
        '151677224326-3guq6i5ef73uokvjf3v83r17nrll498c.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectName',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrIPV69WST8eYp-FSdJ6kd5l8n87SIeXE',
    appId: '1:151677224326:ios:098f57cc6b742261289807',
    messagingSenderId: '151677224326',
    projectId: 'skillghor-145e9',
    storageBucket: 'skillghor-145e9.firebasestorage.app',
    iosClientId:
        '151677224326-3guq6i5ef73uokvjf3v83r17nrll498c.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectName',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDelMMDyiavhEWIh7wN8jgnFKvXm4fsAto',
    appId: '1:151677224326:web:edaad83f148ab52b289807',
    messagingSenderId: '151677224326',
    projectId: 'skillghor-145e9',
    authDomain: 'skillghor-145e9.firebaseapp.com',
    storageBucket: 'skillghor-145e9.firebasestorage.app',
    measurementId: 'G-HLTNWFKLND',
  );
}
